# Created by: Michael Johnson <ahze@FreeBSD.org>
# $FreeBSD: head/print/gutenprint-cups/Makefile 340722 2014-01-22 17:00:46Z mat $
#    $MCom: ports/print/gutenprint-cups/Makefile,v 1.1 2007/03/30 16:42:47 ahze Exp $

PORTEPOCH=	0
PKGNAMESUFFIX=	-cups

MAINTAINER=	cmt@burggraben.net
COMMENT=	GutenPrint CUPS drivers

LICENSE=	GPLv2

MASTERDIR=	${.CURDIR}/../../print/gutenprint-base

GUT_SLAVE=	cups
PLIST=		${.CURDIR}/pkg-plist

.include "${MASTERDIR}/Makefile"
